version: 2
updates:
- package-ecosystem: terraform
  directory: "/environments/alpha"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - smark88
  - fboulnois
  labels:
  - dependencies
  - dependabot
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: terraform
  directory: "/environments/perf"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - smark88
  - fboulnois
  labels:
  - dependencies
  - dependabot
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: terraform
  directory: "/environments/staging"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: master
  reviewers:
  - smark88
  - fboulnois
  labels:
  - dependencies
  - dependabot
  commit-message:
    prefix: chore
    include: scope
