version: 1
update_configs:
# Keep package.json (& lockfiles) secure and up-to-date,
# batching pull requests daily
  - package_manager: "terraform"
    directory: "/environments/alpha"
    update_schedule: "daily"
    target_branch: "master"
    default_reviewers:
      - "smark88"
      - "fboulnois"
    default_labels:
      - "dependencies"
      - "dependabot"
    commit_message:
      prefix: "chore"
      include_scope: true
  - package_manager: "terraform"
    directory: "/environments/perf"
    update_schedule: "daily"
    target_branch: "master"
    default_reviewers:
      - "smark88"
      - "fboulnois"
    default_labels:
      - "dependencies"
      - "dependabot"
    commit_message:
      prefix: "chore"
      include_scope: true
  - package_manager: "terraform"
    directory: "/environments/staging"
    update_schedule: "daily"
    target_branch: "master"
    default_reviewers:
      - "smark88"
      - "fboulnois"
    default_labels:
      - "dependencies"
      - "dependabot"
    commit_message:
      prefix: "chore"
      include_scope: true
