name: 'Terraform GitHub Actions to validate TF files'
on:
  - pull_request
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'consul-templete Download/Install'
        run: |
          wget https://releases.hashicorp.com/consul-template/0.24.1/consul-template_0.24.1_linux_amd64.zip
          unzip consul-template_0.24.1_linux_amd64.zip
          chmod u+x consul-template
          cp -v consul-template /tmp/consul-template
        env:
          CONSUL_TOKEN: ${{ secrets.CONSUL_TOKEN }}
          ENVIRONMENT: dev
          SUFFIX: dev
      - name: consul-templete render
        run: |
#          find /home/runner/work/terraform-jade -name "*.ctmpl" -print
          /tmp/consul-template -once -log-level=err \
          -template=/home/runner/work/terraform-jade/terraform-jade/variables.tf.ctmpl:/home/runner/work/terraform-jade/terraform-jade/variables.tf
          ls -al /home/runner/work/terraform-jade/terraform-jade/variables*
        env:
          CONSUL_TOKEN: ${{ secrets.CONSUL_TOKEN }}
          ENVIRONMENT: dev
          SUFFIX: dev
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'validate'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: 'Terraform Plan'
#        uses: hashicorp/terraform-github-actions@master
#        with:
#          tf_actions_version: 0.12.13
#          tf_actions_subcommand: 'plan'
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
