name: 'Terraform GitHub Actions to validate TF files'
on:
  - pull_request
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'fmt'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'consul-templete Download/Install'
        run: |
          wget https://releases.hashicorp.com/consul-template/0.24.1/consul-template_0.24.1_linux_amd64.zip
          unzip consul-template_0.24.1_linux_amd64.zip
          chmod u+x consul-template
          cp -v consul-template /tmp/consul-template
          /tmp/consul-template --version
        env:
          VAULT_TOKEN: ${{ secrets.CONSUL_TOKEN }}
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          ENVIRONMENT: dev
          SUFFIX: dev
      - name: consul-template render env_creds template
        run: |
        ls env_*.ctmpl | while read file
          do
            rootname="${file%.ctmpl}"
            newname=`echo $rootname | sed -e "s;^env_;${ENVIRONMENT}_;"`
            echo "$rootname -> $newname"
            /usr/local/bin/consul-template \
                -once \
                -config=/etc/consul-template/config/config.json \
                -log-level=err \
                -template=${file}:${newname}
          done
        env:
          VAULT_TOKEN: ${{ secrets.CONSUL_TOKEN }}
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          ENVIRONMENT: dev
          SUFFIX: dev
      - name: consul-template render other templates
        run: |
          find . -name "*.ctmpl" -print | grep -Ev "^./env"| while read file
          do
            rootname="${file%.ctmpl}"
            echo "$file -> $rootname"
            /tmp/consul-template \
                -once \
                -vault-addr "${VAULT_ADDR}" \
                -log-level=err \
                -template=${file}:${rootname}
          done
        env:
          VAULT_TOKEN: ${{ secrets.CONSUL_TOKEN }}
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          ENVIRONMENT: dev
          SUFFIX: dev
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'validate'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
